# Generated by Django 6.0.8 on 2026-09-30 13:41

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="extra data"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("code", models.SlugField(unique=True, verbose_name="code")),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("zero_rated", "Zero Rated"),
                            ("exempt", "VAT Exempt"),
                        ],
                        default="standard",
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Override VAT rate (e.g. 0.0750). Leave blank to use the global default.",
                        max_digits=5,
                        null=True,
                        verbose_name="rate",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="description")),
            ],
            options={
                "verbose_name": "tax category",
                "verbose_name_plural": "tax categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PriceBreakdown",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="extra data"),
                ),
                ("object_id", models.UUIDField(blank=True, null=True, verbose_name="object ID")),
                ("quantity", models.PositiveIntegerField(default=1, verbose_name="quantity")),
                (
                    "unit_price_net",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="unit price (net)"
                    ),
                ),
                (
                    "unit_vat",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="unit VAT",
                    ),
                ),
                (
                    "unit_price_gross",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="unit price (gross)"
                    ),
                ),
                (
                    "vat_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0750"),
                        max_digits=5,
                        verbose_name="VAT rate",
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="NGN", max_length=10, verbose_name="currency"),
                ),
                (
                    "line_net",
                    models.DecimalField(decimal_places=2, max_digits=14, verbose_name="line net"),
                ),
                (
                    "line_vat",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="line VAT",
                    ),
                ),
                (
                    "line_gross",
                    models.DecimalField(decimal_places=2, max_digits=14, verbose_name="line gross"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "price breakdown",
                "verbose_name_plural": "price breakdowns",
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"], name="pricing_breakdown_obj_idx"
                    )
                ],
            },
        ),
    ]
