# Generated by Django 6.0.8 on 2026-09-30 14:33

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchTerm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="extra data"),
                ),
                ("term", models.CharField(max_length=255, unique=True, verbose_name="term")),
                (
                    "count",
                    models.PositiveIntegerField(db_index=True, default=0, verbose_name="searches"),
                ),
                (
                    "is_hidden",
                    models.BooleanField(default=False, verbose_name="hidden from trending"),
                ),
            ],
            options={
                "verbose_name": "search term",
                "verbose_name_plural": "search terms",
                "ordering": ["-count"],
            },
        ),
        migrations.CreateModel(
            name="ProductQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="extra data"),
                ),
                ("object_id", models.UUIDField(verbose_name="product ID")),
                ("question", models.TextField(max_length=1000, verbose_name="question")),
                (
                    "is_approved",
                    models.BooleanField(db_index=True, default=False, verbose_name="approved"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "product question",
                "verbose_name_plural": "product questions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductAnswer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="extra data"),
                ),
                ("answer", models.TextField(max_length=2000, verbose_name="answer")),
                (
                    "is_official",
                    models.BooleanField(
                        default=False,
                        help_text="From staff or the seller.",
                        verbose_name="official answer",
                    ),
                ),
                ("is_approved", models.BooleanField(default=True, verbose_name="approved")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_answers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="flexcommerce_engagement.productquestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "product answer",
                "verbose_name_plural": "product answers",
                "ordering": ["-is_official", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="extra data"),
                ),
                ("object_id", models.UUIDField(verbose_name="product ID")),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="rating",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, verbose_name="title")),
                ("body", models.TextField(max_length=5000, verbose_name="body")),
                ("image_urls", models.JSONField(blank=True, default=list, verbose_name="photos")),
                (
                    "is_verified_purchase",
                    models.BooleanField(default=False, verbose_name="verified purchase"),
                ),
                (
                    "is_approved",
                    models.BooleanField(db_index=True, default=False, verbose_name="approved"),
                ),
                ("is_rejected", models.BooleanField(default=False, verbose_name="rejected")),
                (
                    "moderation_note",
                    models.CharField(blank=True, max_length=255, verbose_name="moderation note"),
                ),
                ("is_featured", models.BooleanField(default=False, verbose_name="featured")),
                (
                    "helpful_count",
                    models.PositiveIntegerField(default=0, verbose_name="helpful votes"),
                ),
                ("reply", models.TextField(blank=True, verbose_name="seller / staff reply")),
                (
                    "replied_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="replied at"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "product review",
                "verbose_name_plural": "product reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecentlyViewed",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="extra data"),
                ),
                ("object_id", models.UUIDField(verbose_name="product ID")),
                (
                    "session_key",
                    models.CharField(
                        blank=True, db_index=True, max_length=40, verbose_name="session key"
                    ),
                ),
                ("view_count", models.PositiveIntegerField(default=1, verbose_name="view count")),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recently_viewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "recently viewed",
                "verbose_name_plural": "recently viewed items",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="RecentSearch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="extra data"),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True, db_index=True, max_length=40, verbose_name="session key"
                    ),
                ),
                ("query", models.CharField(max_length=255, verbose_name="query")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recent_searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "recent search",
                "verbose_name_plural": "recent searches",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewVote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="extra data"),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="flexcommerce_engagement.productreview",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "review vote",
                "verbose_name_plural": "review votes",
            },
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="extra data"),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True, db_index=True, max_length=40, verbose_name="session key"
                    ),
                ),
                (
                    "name",
                    models.CharField(default="My Wishlist", max_length=200, verbose_name="name"),
                ),
                ("is_default", models.BooleanField(default=False, verbose_name="default list")),
                (
                    "visibility",
                    models.CharField(
                        choices=[("private", "Private"), ("public", "Public")],
                        default="private",
                        max_length=10,
                        verbose_name="visibility",
                    ),
                ),
                (
                    "share_token",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        unique=True,
                        verbose_name="share token",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "wishlist",
                "verbose_name_plural": "wishlists",
                "ordering": ["-is_default", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="WishlistItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="extra data"),
                ),
                ("object_id", models.UUIDField(verbose_name="product ID")),
                ("note", models.CharField(blank=True, max_length=255, verbose_name="note")),
                (
                    "added_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="price when added",
                    ),
                ),
                (
                    "price_alert_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="price-drop alert sent"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
                (
                    "wishlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="flexcommerce_engagement.wishlist",
                    ),
                ),
            ],
            options={
                "verbose_name": "wishlist item",
                "verbose_name_plural": "wishlist items",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="productquestion",
            index=models.Index(
                fields=["content_type", "object_id", "is_approved"], name="eng_question_product_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productreview",
            index=models.Index(
                fields=["content_type", "object_id", "is_approved"], name="eng_review_product_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productreview",
            index=models.Index(fields=["rating", "is_approved"], name="eng_review_rating_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="productreview",
            unique_together={("user", "content_type", "object_id")},
        ),
        migrations.AddIndex(
            model_name="recentlyviewed",
            index=models.Index(fields=["user", "updated_at"], name="eng_rv_user_idx"),
        ),
        migrations.AddIndex(
            model_name="recentlyviewed",
            index=models.Index(fields=["session_key", "updated_at"], name="eng_rv_session_idx"),
        ),
        migrations.AddIndex(
            model_name="recentsearch",
            index=models.Index(fields=["user", "updated_at"], name="eng_rs_user_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="reviewvote",
            unique_together={("review", "user")},
        ),
        migrations.AddIndex(
            model_name="wishlist",
            index=models.Index(fields=["user", "visibility"], name="eng_wishlist_user_idx"),
        ),
        migrations.AddConstraint(
            model_name="wishlist",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("user",),
                name="eng_one_default_wishlist",
            ),
        ),
        migrations.AddIndex(
            model_name="wishlistitem",
            index=models.Index(
                fields=["content_type", "object_id"], name="eng_wishitem_product_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="wishlistitem",
            unique_together={("wishlist", "content_type", "object_id")},
        ),
    ]
