# Generated by Django 6.0.8 on 2026-09-30 14:07

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import flexcommerce_cart.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="extra data"),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True, db_index=True, max_length=40, verbose_name="session key"
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=flexcommerce_cart.models.new_cart_token,
                        editable=False,
                        max_length=64,
                        unique=True,
                        verbose_name="cart token",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("locked", "Locked"),
                            ("ordered", "Ordered"),
                            ("merged", "Merged"),
                            ("abandoned", "Abandoned"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="NGN", max_length=10, verbose_name="currency"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Guest contact for cart recovery.",
                        max_length=254,
                        verbose_name="contact email",
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="contact phone"),
                ),
                (
                    "coupon_code",
                    models.CharField(blank=True, max_length=100, verbose_name="coupon code"),
                ),
                (
                    "coupon_error",
                    models.CharField(blank=True, max_length=255, verbose_name="coupon message"),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="discount amount",
                    ),
                ),
                ("free_shipping", models.BooleanField(default=False, verbose_name="free shipping")),
                (
                    "shipping_method_id",
                    models.UUIDField(blank=True, null=True, verbose_name="shipping method ID"),
                ),
                (
                    "subtotal_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="subtotal",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="VAT included",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="total",
                    ),
                ),
                (
                    "items_count",
                    models.PositiveIntegerField(default=0, verbose_name="units in cart"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="expires at"),
                ),
                (
                    "last_activity",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="last activity"
                    ),
                ),
                (
                    "abandoned_notified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="abandonment notified at"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="carts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "cart",
                "verbose_name_plural": "carts",
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="extra data"),
                ),
                ("object_id", models.UUIDField(verbose_name="product ID")),
                ("quantity", models.PositiveIntegerField(default=1, verbose_name="quantity")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="unit price",
                    ),
                ),
                (
                    "unit_price_with_tax",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="unit price with tax",
                    ),
                ),
                (
                    "unit_net",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="unit net",
                    ),
                ),
                (
                    "vat_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0750"),
                        max_digits=5,
                        verbose_name="VAT rate",
                    ),
                ),
                (
                    "vat_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="unit VAT",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="line discount",
                    ),
                ),
                (
                    "is_saved_for_later",
                    models.BooleanField(default=False, verbose_name="saved for later"),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="flexcommerce_cart.cart",
                        verbose_name="cart",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="product type",
                    ),
                ),
            ],
            options={
                "verbose_name": "cart item",
                "verbose_name_plural": "cart items",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="extra data"),
                ),
                ("object_id", models.UUIDField(verbose_name="product ID")),
                (
                    "saved_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="saved price",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "saved item",
                "verbose_name_plural": "saved items",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(fields=["session_key", "status"], name="cart_session_status_idx"),
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(fields=["user", "status"], name="cart_user_status_idx"),
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(fields=["status", "last_activity"], name="cart_status_activity_idx"),
        ),
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status", "active"),
                    ("user__isnull", True),
                    models.Q(("session_key", ""), _negated=True),
                ),
                fields=("session_key",),
                name="unique_active_session_cart",
            ),
        ),
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("user",),
                name="unique_active_user_cart",
            ),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(fields=["content_type", "object_id"], name="cart_item_product_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "content_type", "object_id")},
        ),
        migrations.AddIndex(
            model_name="saveditem",
            index=models.Index(fields=["content_type", "object_id"], name="cart_saved_product_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="saveditem",
            unique_together={("user", "content_type", "object_id")},
        ),
    ]
