# Generated by Django 6.0.8 on 2026-09-30 14:23

import django.db.models.deletion
import flexcommerce_payments.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flexcommerce_orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentWebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='extra data')),
                ('provider', models.CharField(max_length=50, verbose_name='provider')),
                ('event_id', models.CharField(blank=True, max_length=200, verbose_name='event ID')),
                ('event_type', models.CharField(blank=True, max_length=100, verbose_name='event type')),
                ('reference', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='reference')),
                ('signature_valid', models.BooleanField(default=False, verbose_name='signature valid')),
                ('processed', models.BooleanField(default=False, verbose_name='processed')),
                ('error', models.CharField(blank=True, max_length=500, verbose_name='error')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='payload')),
            ],
            options={
                'verbose_name': 'payment webhook',
                'verbose_name_plural': 'payment webhooks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'event_id'], name='payments_webhook_event_idx')],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='extra data')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='balance')),
                ('currency', models.CharField(default='NGN', max_length=10, verbose_name='currency')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'wallet',
                'verbose_name_plural': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='extra data')),
                ('type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10, verbose_name='type')),
                ('source', models.CharField(choices=[('topup', 'Top-up'), ('refund', 'Refund'), ('purchase', 'Purchase'), ('adjustment', 'Adjustment'), ('cashback', 'Cashback / reward'), ('reversal', 'Reversal')], max_length=20, verbose_name='source')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='amount')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='balance after')),
                ('reference', models.CharField(max_length=150, unique=True, verbose_name='reference')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='flexcommerce_orders.order')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='flexcommerce_payments.wallet')),
            ],
            options={
                'verbose_name': 'wallet transaction',
                'verbose_name_plural': 'wallet transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='extra data')),
                ('purpose', models.CharField(choices=[('order', 'Order'), ('wallet_topup', 'Wallet top-up')], default='order', max_length=20, verbose_name='purpose')),
                ('provider', models.CharField(db_index=True, max_length=50, verbose_name='provider')),
                ('reference', models.CharField(default=flexcommerce_payments.models.new_reference, max_length=100, unique=True, verbose_name='reference')),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='provider reference')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='amount')),
                ('amount_received', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='amount received')),
                ('currency', models.CharField(default='NGN', max_length=10, verbose_name='currency')),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('success', 'Successful'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], db_index=True, default='initiated', max_length=20, verbose_name='status')),
                ('channel', models.CharField(blank=True, help_text='card, bank, ussd, transfer...', max_length=50, verbose_name='channel')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='payer email')),
                ('authorization_url', models.URLField(blank=True, max_length=1000, verbose_name='authorization URL')),
                ('callback_url', models.URLField(blank=True, max_length=1000, verbose_name='callback URL')),
                ('failure_reason', models.CharField(blank=True, max_length=500, verbose_name='failure reason')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verified at')),
                ('gateway_response', models.JSONField(blank=True, default=dict, verbose_name='gateway response')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='flexcommerce_orders.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', 'status'], name='payments_order_status_idx')],
            },
        ),
    ]
