# Generated by Django 6.0.8 on 2026-09-30 14:38

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flexcommerce_orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='extra data')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='shop name')),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('logo_url', models.URLField(blank=True, max_length=500, verbose_name='logo URL')),
                ('banner_url', models.URLField(blank=True, max_length=500, verbose_name='banner URL')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='support email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='support phone')),
                ('address', models.JSONField(blank=True, default=dict, verbose_name='business address')),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], db_index=True, default='pending', max_length=20, verbose_name='status')),
                ('is_official_store', models.BooleanField(default=False, verbose_name='official store')),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=4, help_text='e.g. 0.1000 for 10%. Blank = MARKETPLACE_COMMISSION_RATE.', max_digits=5, null=True, verbose_name='commission rate')),
                ('business_registration_number', models.CharField(blank=True, max_length=50, verbose_name='CAC / registration number')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='TIN')),
                ('kyc_documents', models.JSONField(blank=True, default=list, help_text='URLs', verbose_name='KYC documents')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='bank name')),
                ('bank_code', models.CharField(blank=True, max_length=20, verbose_name='bank code')),
                ('account_number', models.CharField(blank=True, max_length=20, verbose_name='account number')),
                ('account_name', models.CharField(blank=True, max_length=150, verbose_name='account name')),
                ('paystack_subaccount', models.CharField(blank=True, max_length=50, verbose_name='Paystack subaccount code')),
                ('rating_avg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3, verbose_name='rating')),
                ('rating_count', models.PositiveIntegerField(default=0, verbose_name='ratings')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('status_reason', models.CharField(blank=True, max_length=255, verbose_name='status reason')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_vendors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'vendor',
                'verbose_name_plural': 'vendors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='extra data')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='amount')),
                ('currency', models.CharField(default='NGN', max_length=10, verbose_name='currency')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20, verbose_name='status')),
                ('reference', models.CharField(blank=True, max_length=200, verbose_name='reference')),
                ('failure_reason', models.CharField(blank=True, max_length=500, verbose_name='failure reason')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
                ('bank_details', models.JSONField(blank=True, default=dict, verbose_name='bank details snapshot')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='flexcommerce_marketplace.vendor')),
            ],
            options={
                'verbose_name': 'payout',
                'verbose_name_plural': 'payouts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='extra data')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('staff', 'Staff')], default='staff', max_length=20, verbose_name='role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_membership', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='flexcommerce_marketplace.vendor')),
            ],
            options={
                'verbose_name': 'vendor member',
                'verbose_name_plural': 'vendor members',
            },
        ),
        migrations.CreateModel(
            name='VendorOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='extra data')),
                ('status', models.CharField(choices=[('pending', 'Awaiting payment'), ('confirmed', 'To fulfil'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20, verbose_name='status')),
                ('gross_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='sales (after discounts)')),
                ('commission_rate', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=5, verbose_name='commission rate')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='commission')),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='refunded')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='delivered at')),
                ('available_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='earnings available at')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_orders', to='flexcommerce_orders.order')),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_orders', to='flexcommerce_marketplace.payout')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_orders', to='flexcommerce_marketplace.vendor')),
            ],
            options={
                'verbose_name': 'vendor order',
                'verbose_name_plural': 'vendor orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vendor', 'status'], name='mkt_vorder_vendor_idx')],
                'unique_together': {('order', 'vendor')},
            },
        ),
    ]
