# Generated by scripts/gen_test_settings.py — edit the template, not this file.
import os
from urllib.parse import urlparse

SECRET_KEY = "test-secret-key-flexcommerce-notifications"
DEBUG = True
DATABASES = {"default": {"ENGINE": "django.db.backends.sqlite3", "NAME": ":memory:"}}
if os.environ.get("FC_TEST_DATABASE_URL"):  # e.g. postgresql://postgres:@127.0.0.1:5432/postgres
    _url = urlparse(os.environ["FC_TEST_DATABASE_URL"])
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": _url.path.lstrip("/") or "postgres",
            "USER": _url.username or "postgres",
            "PASSWORD": _url.password or "",
            "HOST": _url.hostname or "localhost",
            "PORT": _url.port or 5432,
            "TEST": {"NAME": "test_flexcommerce_notifications"},
        }
    }
INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.admin",
    "django.contrib.messages",
    "rest_framework",
    "flexcommerce_core",
    "flexcommerce_notifications",
]
MIDDLEWARE = [
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
]
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.request",
            ]
        },
    }
]
ROOT_URLCONF = "tests.urls"
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
USE_TZ = True
CACHES = {"default": {"BACKEND": "django.core.cache.backends.locmem.LocMemCache"}}
PASSWORD_HASHERS = ["django.contrib.auth.hashers.MD5PasswordHasher"]
EMAIL_BACKEND = "django.core.mail.backends.locmem.EmailBackend"
FLEXCOMMERCE = {}
