# Generated by Django 6.0.8 on 2026-09-30 13:33

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='extra data')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('logo_url', models.URLField(blank=True, max_length=500, verbose_name='logo URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('is_official_store', models.BooleanField(default=False, verbose_name='official store')),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='extra data')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='image URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('path', models.CharField(db_index=True, default='', editable=False, max_length=1000, verbose_name='path')),
                ('depth', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='depth')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='meta title')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='meta description')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='flexcommerce_catalog.category', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['path', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='extra data')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True, verbose_name='slug')),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='short description')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], db_index=True, default='draft', max_length=10, verbose_name='status')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='featured')),
                ('vendor_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='vendor ID')),
                ('specifications', models.JSONField(blank=True, default=dict, help_text='Key/value specs, e.g. {"RAM": "8GB"}', verbose_name='specifications')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='tags')),
                ('vat_exempt', models.BooleanField(default=False, verbose_name='VAT exempt')),
                ('tax_category_code', models.SlugField(blank=True, help_text='Code of a flexcommerce_pricing TaxCategory.', verbose_name='tax category code')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='meta title')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='meta description')),
                ('min_price', models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='min price')),
                ('max_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='max price')),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, help_text="Old price of the cheapest variant (for 'x% off' badges).", max_digits=14, null=True, verbose_name='compare-at price')),
                ('in_stock', models.BooleanField(db_index=True, default=True, verbose_name='in stock')),
                ('rating_avg', models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0.00'), max_digits=3, verbose_name='average rating')),
                ('rating_count', models.PositiveIntegerField(default=0, verbose_name='rating count')),
                ('sold_count', models.PositiveIntegerField(db_index=True, default=0, verbose_name='units sold')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='published at')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='flexcommerce_catalog.brand', verbose_name='brand')),
                ('categories', models.ManyToManyField(blank=True, related_name='products', to='flexcommerce_catalog.category', verbose_name='categories')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='extra data')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='SKU')),
                ('name', models.CharField(blank=True, help_text='e.g. "Red / XL"', max_length=255, verbose_name='option name')),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='e.g. {"color": "Red"}', verbose_name='attributes')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='price')),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='compare-at price')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='cost price')),
                ('weight', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10, verbose_name='weight (kg)')),
                ('barcode', models.CharField(blank=True, max_length=64, verbose_name='barcode')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('is_default', models.BooleanField(default=False, verbose_name='is default')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='flexcommerce_catalog.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'product variant',
                'verbose_name_plural': 'product variants',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='extra data')),
                ('image', models.FileField(blank=True, upload_to='flexcommerce/products/%Y/%m/', verbose_name='image file')),
                ('url', models.URLField(blank=True, help_text='Use instead of a file (e.g. CDN).', max_length=500, verbose_name='image URL')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='alt text')),
                ('is_primary', models.BooleanField(default=False, verbose_name='is primary')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='flexcommerce_catalog.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='flexcommerce_catalog.productvariant')),
            ],
            options={
                'verbose_name': 'product image',
                'verbose_name_plural': 'product images',
                'ordering': ['-is_primary', 'sort_order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', '-published_at'], name='catalog_prod_status_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'min_price'], name='catalog_prod_status_price_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['vendor_id', 'status'], name='catalog_prod_vendor_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'is_active'], name='catalog_variant_active_idx'),
        ),
    ]
