# Generated by Django 6.0.8 on 2026-09-30 13:45

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="extra data"),
                ),
                ("object_id", models.UUIDField(db_index=True, verbose_name="product ID")),
                (
                    "sku",
                    models.CharField(blank=True, db_index=True, max_length=100, verbose_name="SKU"),
                ),
                ("on_hand", models.PositiveIntegerField(default=0, verbose_name="on hand")),
                ("reserved", models.PositiveIntegerField(default=0, verbose_name="reserved")),
                ("sold", models.PositiveIntegerField(default=0, verbose_name="sold")),
                (
                    "reorder_point",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Alert when available stock falls to this level. Blank = global LOW_STOCK_THRESHOLD.",
                        null=True,
                        verbose_name="low-stock threshold",
                    ),
                ),
                (
                    "allow_oversell",
                    models.BooleanField(
                        default=False,
                        help_text="Allow purchases beyond on-hand stock.",
                        verbose_name="allow oversell / backorder",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="product type",
                    ),
                ),
            ],
            options={
                "verbose_name": "inventory item",
                "verbose_name_plural": "inventory items",
            },
        ),
        migrations.CreateModel(
            name="StockAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="extra data"),
                ),
                ("object_id", models.UUIDField(verbose_name="product ID")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="email")),
                ("phone", models.CharField(blank=True, max_length=20, verbose_name="phone")),
                (
                    "notified_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="notified at"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "back-in-stock alert",
                "verbose_name_plural": "back-in-stock alerts",
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="extra data"),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("restock", "Restock"),
                            ("sale", "Sale"),
                            ("return", "Return"),
                            ("adjustment", "Adjustment"),
                        ],
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        help_text="Positive adds stock, negative removes it.",
                        verbose_name="quantity",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="note")),
                (
                    "reference",
                    models.CharField(blank=True, max_length=100, verbose_name="reference"),
                ),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="flexcommerce_inventory.inventoryitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "stock movement",
                "verbose_name_plural": "stock movements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockReservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="extra data"),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="quantity")),
                (
                    "order_ref",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, verbose_name="order reference"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("fulfilled", "Fulfilled"),
                            ("released", "Released"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="expires at"),
                ),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="flexcommerce_inventory.inventoryitem",
                        verbose_name="inventory item",
                    ),
                ),
            ],
            options={
                "verbose_name": "stock reservation",
                "verbose_name_plural": "stock reservations",
            },
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(fields=["on_hand", "reserved"], name="inv_item_levels_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="inventoryitem",
            unique_together={("content_type", "object_id")},
        ),
        migrations.AddIndex(
            model_name="stockalert",
            index=models.Index(
                fields=["content_type", "object_id", "notified_at"], name="inv_alert_pending_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockalert",
            constraint=models.UniqueConstraint(
                condition=models.Q(("notified_at__isnull", True), ("user__isnull", False)),
                fields=("content_type", "object_id", "user"),
                name="inv_alert_unique_user_pending",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockalert",
            constraint=models.UniqueConstraint(
                condition=models.Q(("notified_at__isnull", True), ("user__isnull", True)),
                fields=("content_type", "object_id", "email"),
                name="inv_alert_unique_email_pending",
            ),
        ),
        migrations.AddIndex(
            model_name="stockreservation",
            index=models.Index(fields=["status", "expires_at"], name="inv_res_status_exp_idx"),
        ),
    ]
