# Generated by Django 6.0.8 on 2026-09-30 14:01

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShippingZone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="extra data"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("zone_code", models.SlugField(unique=True, verbose_name="zone code")),
                (
                    "states",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="State names covered. Overrides the built-in Nigerian mapping.",
                        verbose_name="states / regions",
                    ),
                ),
                (
                    "countries",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Country names or ISO codes, e.g. ["Ghana", "GH"]. Leave empty for the home country.',
                        verbose_name="countries",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="is active")),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="sort order"),
                ),
            ],
            options={
                "verbose_name": "shipping zone",
                "verbose_name_plural": "shipping zones",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ShippingMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="extra data"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                ("code", models.SlugField(blank=True, verbose_name="code")),
                ("carrier", models.CharField(blank=True, max_length=100, verbose_name="carrier")),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, verbose_name="description"),
                ),
                (
                    "rate_type",
                    models.CharField(
                        choices=[
                            ("flat", "Flat Rate"),
                            ("per_item", "Per Item"),
                            ("weight", "Weight Based"),
                            ("free", "Free Shipping"),
                        ],
                        default="flat",
                        max_length=20,
                        verbose_name="rate type",
                    ),
                ),
                (
                    "base_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="base rate",
                    ),
                ),
                (
                    "per_item_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="per item rate",
                    ),
                ),
                (
                    "weight_tiers",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"max_kg": 1, "rate": 1500}, {"max_kg": 5, "rate": 3000}] — cheapest tier that fits.',
                        verbose_name="weight tiers",
                    ),
                ),
                (
                    "per_kg_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Charged per kg above the heaviest tier (or per kg if there are no tiers).",
                        max_digits=14,
                        verbose_name="rate per extra kg",
                    ),
                ),
                (
                    "max_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="max weight (kg)",
                    ),
                ),
                (
                    "free_shipping_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="free shipping from",
                    ),
                ),
                ("is_pickup", models.BooleanField(default=False, verbose_name="is pickup")),
                (
                    "pay_on_delivery",
                    models.BooleanField(default=True, verbose_name="pay on delivery available"),
                ),
                (
                    "estimated_days_min",
                    models.PositiveSmallIntegerField(default=1, verbose_name="min delivery days"),
                ),
                (
                    "estimated_days_max",
                    models.PositiveSmallIntegerField(default=5, verbose_name="max delivery days"),
                ),
                (
                    "apply_vat",
                    models.BooleanField(default=False, verbose_name="apply VAT to shipping"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="is active")),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="sort order"),
                ),
                (
                    "zones",
                    models.ManyToManyField(
                        blank=True, related_name="methods", to="flexcommerce_shipping.shippingzone"
                    ),
                ),
            ],
            options={
                "verbose_name": "shipping method",
                "verbose_name_plural": "shipping methods",
                "ordering": ["sort_order", "base_rate"],
            },
        ),
        migrations.CreateModel(
            name="PickupStation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="extra data"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                ("code", models.SlugField(unique=True, verbose_name="code")),
                ("state", models.CharField(max_length=100, verbose_name="state")),
                ("city", models.CharField(max_length=100, verbose_name="city")),
                ("address", models.CharField(max_length=500, verbose_name="address")),
                ("landmark", models.CharField(blank=True, max_length=255, verbose_name="landmark")),
                ("phone", models.CharField(blank=True, max_length=20, verbose_name="phone")),
                (
                    "opening_hours",
                    models.CharField(blank=True, max_length=200, verbose_name="opening hours"),
                ),
                (
                    "fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Overrides the pickup method's rate for this station.",
                        max_digits=14,
                        null=True,
                        verbose_name="pickup fee",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="longitude",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="is active")),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pickup_stations",
                        to="flexcommerce_shipping.shippingzone",
                    ),
                ),
            ],
            options={
                "verbose_name": "pickup station",
                "verbose_name_plural": "pickup stations",
                "ordering": ["state", "city", "name"],
                "indexes": [
                    models.Index(fields=["state", "is_active"], name="ship_station_state_idx")
                ],
            },
        ),
    ]
