# Generated by Django 6.0.8 on 2026-09-30 14:44

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="extra data"),
                ),
                ("token", models.CharField(max_length=512, unique=True, verbose_name="token")),
                (
                    "platform",
                    models.CharField(
                        choices=[("android", "Android"), ("ios", "iOS"), ("web", "Web")],
                        default="android",
                        max_length=10,
                        verbose_name="platform",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="is active")),
                (
                    "last_used_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="last used"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "device token",
                "verbose_name_plural": "device tokens",
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="extra data"),
                ),
                (
                    "email_order_updates",
                    models.BooleanField(default=True, verbose_name="email: order updates"),
                ),
                (
                    "email_marketing",
                    models.BooleanField(default=False, verbose_name="email: offers & reminders"),
                ),
                (
                    "email_abandoned_cart",
                    models.BooleanField(default=True, verbose_name="email: abandoned cart"),
                ),
                (
                    "sms_order_updates",
                    models.BooleanField(default=True, verbose_name="SMS: order updates"),
                ),
                (
                    "sms_marketing",
                    models.BooleanField(default=False, verbose_name="SMS: offers & reminders"),
                ),
                (
                    "push_order_updates",
                    models.BooleanField(default=True, verbose_name="push: order updates"),
                ),
                (
                    "push_marketing",
                    models.BooleanField(default=False, verbose_name="push: offers & reminders"),
                ),
                (
                    "in_app_marketing",
                    models.BooleanField(default=True, verbose_name="in-app: offers & reminders"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "notification preference",
                "verbose_name_plural": "notification preferences",
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="extra data"),
                ),
                ("event", models.CharField(db_index=True, max_length=100, verbose_name="event")),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push"),
                            ("in_app", "In-app"),
                        ],
                        max_length=10,
                        verbose_name="channel",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "subject",
                    models.CharField(blank=True, max_length=255, verbose_name="subject / title"),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Django template syntax, e.g. {{ order_number }}.",
                        verbose_name="body",
                    ),
                ),
                ("html_body", models.TextField(blank=True, verbose_name="HTML body (email)")),
                ("is_active", models.BooleanField(default=True, verbose_name="is active")),
            ],
            options={
                "verbose_name": "notification template",
                "verbose_name_plural": "notification templates",
                "unique_together": {("event", "channel")},
            },
        ),
        migrations.CreateModel(
            name="InAppNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="extra data"),
                ),
                ("event", models.CharField(max_length=100, verbose_name="event")),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("body", models.TextField(verbose_name="body")),
                ("data", models.JSONField(blank=True, default=dict, verbose_name="data")),
                ("read_at", models.DateTimeField(blank=True, null=True, verbose_name="read at")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inbox",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "in-app notification",
                "verbose_name_plural": "in-app notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "read_at"], name="notif_inbox_unread_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="extra data"),
                ),
                ("event", models.CharField(db_index=True, max_length=100, verbose_name="event")),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push"),
                            ("in_app", "In-app"),
                        ],
                        max_length=10,
                        verbose_name="channel",
                    ),
                ),
                (
                    "recipient",
                    models.CharField(
                        help_text="Email, phone, device token or user id.",
                        max_length=255,
                        verbose_name="recipient",
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=255, verbose_name="subject")),
                ("body", models.TextField(blank=True, verbose_name="body")),
                ("html_body", models.TextField(blank=True, verbose_name="HTML body")),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Push / in-app payload (e.g. deep link).",
                        verbose_name="data",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0, verbose_name="attempts")),
                (
                    "next_attempt_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="next attempt at"),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="error message")),
                ("provider", models.CharField(blank=True, max_length=100, verbose_name="provider")),
                (
                    "provider_message_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="provider message ID"
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True, verbose_name="sent at")),
                (
                    "context_snapshot",
                    models.JSONField(blank=True, default=dict, verbose_name="context snapshot"),
                ),
                (
                    "dedupe_key",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="dedupe key",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "notification log",
                "verbose_name_plural": "notification logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["event", "status"], name="notif_event_status_idx"),
                    models.Index(fields=["recipient", "channel"], name="notif_recipient_idx"),
                    models.Index(fields=["user", "channel"], name="notif_user_channel_idx"),
                    models.Index(fields=["status", "next_attempt_at"], name="notif_due_idx"),
                ],
            },
        ),
    ]
