# Generated by Django 6.0.8 on 2026-09-30 14:50

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyRevenueSummary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="extra data"),
                ),
                ("date", models.DateField(db_index=True, verbose_name="date")),
                (
                    "currency",
                    models.CharField(default="NGN", max_length=10, verbose_name="currency"),
                ),
                ("order_count", models.PositiveIntegerField(default=0, verbose_name="orders")),
                ("units_sold", models.PositiveIntegerField(default=0, verbose_name="units sold")),
                (
                    "gross_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=16,
                        verbose_name="gross sales",
                    ),
                ),
                (
                    "net_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=16,
                        verbose_name="net sales (ex VAT)",
                    ),
                ),
                (
                    "tax_collected",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=16, verbose_name="VAT"
                    ),
                ),
                (
                    "shipping_collected",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=16,
                        verbose_name="shipping",
                    ),
                ),
                (
                    "discount_given",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=16,
                        verbose_name="discounts",
                    ),
                ),
                (
                    "refund_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=16,
                        verbose_name="refunds",
                    ),
                ),
                (
                    "average_order_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=16,
                        verbose_name="average order value",
                    ),
                ),
                (
                    "cancelled_order_count",
                    models.PositiveIntegerField(default=0, verbose_name="cancelled orders"),
                ),
                (
                    "abandoned_cart_count",
                    models.PositiveIntegerField(default=0, verbose_name="abandoned carts"),
                ),
                (
                    "new_customers",
                    models.PositiveIntegerField(default=0, verbose_name="new customers"),
                ),
            ],
            options={
                "verbose_name": "daily revenue summary",
                "verbose_name_plural": "daily revenue summaries",
                "ordering": ["-date"],
                "unique_together": {("date", "currency")},
            },
        ),
        migrations.CreateModel(
            name="AnalyticsEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="extra data"),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("order.created", "Order Created"),
                            ("order.confirmed", "Order Confirmed"),
                            ("order.paid", "Order Paid"),
                            ("order.cancelled", "Order Cancelled"),
                            ("order.refunded", "Order Refunded"),
                            ("refund.processed", "Refund Processed"),
                            ("cart.abandoned", "Cart Abandoned"),
                            ("cart.recovered", "Cart Recovered"),
                            ("product.viewed", "Product Viewed"),
                            ("coupon.used", "Coupon Used"),
                            ("review.submitted", "Review Submitted"),
                        ],
                        db_index=True,
                        max_length=50,
                        verbose_name="event type",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(blank=True, max_length=40, verbose_name="session key"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="amount",
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="NGN", max_length=10, verbose_name="currency"),
                ),
                (
                    "vendor_id",
                    models.UUIDField(
                        blank=True, db_index=True, null=True, verbose_name="vendor ID"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, verbose_name="reference"
                    ),
                ),
                ("meta", models.JSONField(blank=True, default=dict, verbose_name="meta")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytics_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "analytics event",
                "verbose_name_plural": "analytics events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "created_at"], name="analytics_type_created_idx"
                    ),
                    models.Index(fields=["user", "event_type"], name="analytics_user_type_idx"),
                    models.Index(
                        fields=["vendor_id", "event_type"], name="analytics_vendor_type_idx"
                    ),
                ],
            },
        ),
    ]
