"""Generate tests/settings.py for each package from one template (dev tool)."""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

APPS = {
    "core": ["flexcommerce_core"],
    "catalog": ["flexcommerce_core", "flexcommerce_catalog"],
    "pricing": ["flexcommerce_core", "flexcommerce_pricing"],
    "inventory": ["flexcommerce_core", "flexcommerce_inventory"],
    "discounts": ["flexcommerce_core", "flexcommerce_discounts"],
    "shipping": ["flexcommerce_core", "flexcommerce_shipping"],
    "cart": ["flexcommerce_core", "flexcommerce_cart"],
    "orders": ["flexcommerce_core", "flexcommerce_orders"],
    "payments": ["flexcommerce_core", "flexcommerce_orders", "flexcommerce_payments"],
    "checkout": ["flexcommerce_core", "flexcommerce_cart", "flexcommerce_orders", "flexcommerce_checkout"],
    "engagement": ["flexcommerce_core", "flexcommerce_engagement"],
    "marketplace": ["flexcommerce_core", "flexcommerce_orders", "flexcommerce_marketplace"],
    "notifications": ["flexcommerce_core", "flexcommerce_notifications"],
    "analytics": [
        "flexcommerce_core",
        "flexcommerce_cart",
        "flexcommerce_orders",
        "flexcommerce_discounts",
        "flexcommerce_analytics",
    ],
}

TEMPLATE = """# Generated by scripts/gen_test_settings.py — edit the template, not this file.
import os
from urllib.parse import urlparse

SECRET_KEY = "test-secret-key-flexcommerce-{name}"
DEBUG = True
DATABASES = {{"default": {{"ENGINE": "django.db.backends.sqlite3", "NAME": ":memory:"}}}}
if os.environ.get("FC_TEST_DATABASE_URL"):  # e.g. postgresql://postgres:@127.0.0.1:5432/postgres
    _url = urlparse(os.environ["FC_TEST_DATABASE_URL"])
    DATABASES = {{
        "default": {{
            "ENGINE": "django.db.backends.postgresql",
            "NAME": _url.path.lstrip("/") or "postgres",
            "USER": _url.username or "postgres",
            "PASSWORD": _url.password or "",
            "HOST": _url.hostname or "localhost",
            "PORT": _url.port or 5432,
            "TEST": {{"NAME": "test_flexcommerce_{name}"}},
        }}
    }}
INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.admin",
    "django.contrib.messages",
    "rest_framework",
{apps}
]
MIDDLEWARE = [
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
]
TEMPLATES = [
    {{
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "APP_DIRS": True,
        "OPTIONS": {{
            "context_processors": [
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.request",
            ]
        }},
    }}
]
ROOT_URLCONF = "tests.urls"
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
USE_TZ = True
CACHES = {{"default": {{"BACKEND": "django.core.cache.backends.locmem.LocMemCache"}}}}
PASSWORD_HASHERS = ["django.contrib.auth.hashers.MD5PasswordHasher"]
EMAIL_BACKEND = "django.core.mail.backends.locmem.EmailBackend"
FLEXCOMMERCE = {flex}
"""

URLS = """from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/", include("flexcommerce_core.urls")),
]
"""

PYTEST_INI = """[pytest]
DJANGO_SETTINGS_MODULE = tests.settings
addopts = -q -p no:cacheprovider
"""


def main(names):
    for name in names or APPS:
        pkg = ROOT / f"flexcommerce-{name}" / "tests"
        extra = pkg / "settings_extra.py"
        flex = "{}"
        apps = list(APPS[name])
        has_test_models = (pkg / "models.py").exists()
        if has_test_models:
            apps.append("tests")
            flex = '{"PRODUCT_MODELS": ["tests.Product"]}'
        body = TEMPLATE.format(name=name, apps="\n".join(f'    "{a}",' for a in apps), flex=flex)
        if extra.exists():
            body += "\nfrom .settings_extra import *  # noqa: E402,F401,F403\n"
        (pkg / "settings.py").write_text(body, encoding="utf-8")
        (pkg / "urls.py").write_text(URLS, encoding="utf-8")
        (pkg.parent / "pytest.ini").write_text(PYTEST_INI, encoding="utf-8")
        print("wrote", pkg / "settings.py")


if __name__ == "__main__":
    main(sys.argv[1:])
