"""
Generate pyproject.toml + MANIFEST.in for every package from one definition.

    python scripts/gen_packaging.py            # write files
    python scripts/gen_packaging.py --check    # fail if any file is out of date (CI)
"""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
VERSION = "1.0.0"
CORE = f"flexcommerce-core>={VERSION},<2"


def dep(name):
    return f"flexcommerce-{name}>={VERSION},<2"


PACKAGES = {
    "core": {
        "description": "Foundation for FlexCommerce: settings, events, hooks, signed webhooks, jobs, audit log and address book",
        "deps": ["Django>=4.2", "djangorestframework>=3.14"],
        "extras": {"celery": ["celery>=5.3"]},
        "keywords": ["webhooks", "audit", "signals"],
    },
    "catalog": {
        "description": "Categories, brands, products with variants and images, search, filters and facets",
        "deps": [CORE],
        "keywords": ["catalog", "products", "variants", "search"],
    },
    "pricing": {
        "description": "Tax categories, VAT calculation and authoritative price quotes",
        "deps": [CORE],
        "keywords": ["vat", "tax", "pricing"],
    },
    "inventory": {
        "description": "Concurrency-safe stock reservations, movements, CSV import and back-in-stock alerts",
        "deps": [CORE],
        "keywords": ["inventory", "stock"],
    },
    "discounts": {
        "description": "Coupons, automatic promotions and flash sales with atomic usage limits",
        "deps": [CORE],
        "keywords": ["coupons", "discounts", "flash-sales"],
    },
    "shipping": {
        "description": "Nigerian shipping zones, rates (flat, per item, weight), pickup stations and ETAs",
        "deps": [CORE],
        "keywords": ["shipping", "delivery", "pickup-stations"],
    },
    "cart": {
        "description": "Session / token / user carts with live pricing, coupons, limits and login merge",
        "deps": [CORE],
        "keywords": ["cart", "basket"],
    },
    "orders": {
        "description": "Order lifecycle: payments, partial shipments, tracking, returns and refunds",
        "deps": [CORE],
        "keywords": ["orders", "returns", "refunds", "shipments"],
    },
    "payments": {
        "description": "Paystack, Flutterwave, bank transfer, pay on delivery and customer wallet",
        "deps": [CORE, dep("orders")],
        "keywords": ["payments", "paystack", "flutterwave", "wallet"],
    },
    "checkout": {
        "description": "Atomic, idempotent checkout tying cart, stock, discounts, shipping, orders and payments",
        "deps": [CORE, dep("cart"), dep("orders")],
        "extras": {"all": [dep("inventory"), dep("discounts"), dep("shipping"), dep("payments")]},
        "keywords": ["checkout"],
    },
    "engagement": {
        "description": "Wishlists, reviews and ratings, product Q&A, recently viewed and trending searches",
        "deps": [CORE],
        "keywords": ["reviews", "wishlist", "ratings"],
    },
    "marketplace": {
        "description": "Multi-vendor marketplace: sellers, order splitting, commissions and payouts",
        "deps": [CORE, dep("orders")],
        "keywords": ["marketplace", "multi-vendor", "sellers", "payouts"],
    },
    "notifications": {
        "description": "Signal-driven email, SMS, push and in-app notifications with an outbox and retries",
        "deps": [CORE],
        "extras": {"fcm": ["google-auth>=2.20", "requests>=2.28"]},
        "keywords": ["notifications", "sms", "email", "push", "termii", "fcm"],
        "data": ["templates/flexcommerce/notifications/*.html"],
    },
    "analytics": {
        "description": "Revenue, product, cart, coupon, vendor and customer reports with CSV export",
        "deps": [CORE],
        "keywords": ["analytics", "reports"],
    },
}

CLASSIFIERS = """    "Development Status :: 5 - Production/Stable",
    "Environment :: Web Environment",
    "Framework :: Django",
    "Framework :: Django :: 4.2",
    "Framework :: Django :: 5.0",
    "Framework :: Django :: 5.1",
    "Framework :: Django :: 5.2",
    "Framework :: Django :: 6.0",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Office/Business :: Financial :: Point-Of-Sale",
    "Topic :: Software Development :: Libraries :: Application Frameworks","""

TEMPLATE = """# Generated by scripts/gen_packaging.py — edit that script, not this file.
[build-system]
requires = ["setuptools>=77", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "{dist}"
version = "{version}"
description = "{description}"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
authors = [{{ name = "NzeStan", email = "nnamaniifeanyi10@gmail.com" }}]
keywords = [{keywords}]
classifiers = [
{classifiers}
]
requires-python = ">=3.10"
dependencies = [
{deps}
]
{extras}
[project.urls]
Homepage = "https://github.com/NzeStan/flex_commerce"
Documentation = "https://github.com/NzeStan/flex_commerce#readme"
Repository = "https://github.com/NzeStan/flex_commerce"
Issues = "https://github.com/NzeStan/flex_commerce/issues"
Changelog = "https://github.com/NzeStan/flex_commerce/blob/main/CHANGELOG.md"

[tool.setuptools.packages.find]
where = ["."]
include = ["{module}*"]
{package_data}"""

MANIFEST = """include README.md
include LICENSE
recursive-include {module} *.py *.html *.txt
prune tests
prune **/__pycache__
global-exclude *.pyc *.pyo *.pyd .DS_Store
"""


def _list(items, indent="    "):
    return "\n".join(f'{indent}"{item}",' for item in items)


def render(name, spec):
    module = f"flexcommerce_{name}" if name != "meta" else "flexcommerce"
    keywords = ", ".join(
        f'"{k}"' for k in ["django", "ecommerce", "flexcommerce", "nigeria", "africa", "drf", *spec.get("keywords", [])]
    )
    extras = ""
    if spec.get("extras"):
        extras = (
            "\n[project.optional-dependencies]\n"
            + "\n".join(
                f"{key} = [{', '.join(repr(v).replace(chr(39), chr(34)) for v in values)}]"
                for key, values in spec["extras"].items()
            )
            + "\n"
        )
    package_data = ""
    if spec.get("data"):
        package_data = (
            f"\n[tool.setuptools.package-data]\n{module} = [{', '.join(chr(34) + d + chr(34) for d in spec['data'])}]\n"
        )
    return TEMPLATE.format(
        dist=spec.get("dist", f"flexcommerce-{name}"),
        version=VERSION,
        description=spec["description"],
        keywords=keywords,
        classifiers=CLASSIFIERS,
        deps=_list(spec["deps"]),
        extras=extras,
        module=module,
        package_data=package_data,
    )


def meta_spec():
    return {
        "dist": "flexcommerce",
        "description": "FlexCommerce: a complete, modular e-commerce and marketplace backend for Django (Nigeria/Africa ready)",
        "deps": [
            dep(n)
            for n in (
                "core",
                "catalog",
                "pricing",
                "inventory",
                "discounts",
                "shipping",
                "cart",
                "orders",
                "payments",
                "checkout",
                "engagement",
                "notifications",
                "analytics",
            )
        ],
        "extras": {
            "marketplace": [dep("marketplace")],
            "celery": ["celery>=5.3"],
            "fcm": ["google-auth>=2.20", "requests>=2.28"],
            "all": [dep("marketplace"), "celery>=5.3", "google-auth>=2.20", "requests>=2.28"],
        },
        "keywords": ["marketplace", "shop", "jumia", "konga"],
    }


def outputs():
    files = {}
    for name, spec in PACKAGES.items():
        base = ROOT / f"flexcommerce-{name}"
        files[base / "pyproject.toml"] = render(name, spec)
        files[base / "MANIFEST.in"] = MANIFEST.format(module=f"flexcommerce_{name}")
    files[ROOT / "flexcommerce-meta" / "pyproject.toml"] = render("meta", meta_spec())
    files[ROOT / "flexcommerce-meta" / "MANIFEST.in"] = MANIFEST.format(module="flexcommerce")
    return files


def main(check=False):
    stale = []
    for path, content in outputs().items():
        if check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(str(path))
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    if stale:
        print("Out of date:\n  " + "\n  ".join(stale))
        sys.exit(1)


if __name__ == "__main__":
    main(check="--check" in sys.argv)
