# Generated by Django 6.0.8 on 2026-09-30 13:24

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("flexcommerce_core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="extra data"),
                ),
                ("event", models.CharField(max_length=100, verbose_name="event")),
                ("payload", models.JSONField(default=dict, verbose_name="payload")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0, verbose_name="attempts")),
                (
                    "next_attempt_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="next attempt at"),
                ),
                (
                    "response_status",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="response status"
                    ),
                ),
                ("response_body", models.TextField(blank=True, verbose_name="response body")),
                ("last_error", models.TextField(blank=True, verbose_name="last error")),
                (
                    "delivered_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="delivered at"),
                ),
            ],
            options={
                "verbose_name": "webhook delivery",
                "verbose_name_plural": "webhook deliveries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="address",
            options={
                "ordering": ["-is_default", "-created_at"],
                "verbose_name": "address",
                "verbose_name_plural": "addresses",
            },
        ),
        migrations.AddField(
            model_name="address",
            name="alt_phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="alternative phone"),
        ),
        migrations.AddField(
            model_name="address",
            name="label",
            field=models.CharField(
                blank=True, help_text='e.g. "Home", "Office"', max_length=50, verbose_name="label"
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="landmark",
            field=models.CharField(blank=True, max_length=255, verbose_name="landmark"),
        ),
        migrations.AddField(
            model_name="address",
            name="lga",
            field=models.CharField(
                blank=True, help_text="Local Government Area", max_length=100, verbose_name="LGA"
            ),
        ),
        migrations.AddField(
            model_name="webhookendpoint",
            name="description",
            field=models.CharField(blank=True, max_length=255, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="address",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="webhookendpoint",
            name="event",
            field=models.CharField(
                choices=[
                    ("*", "All events"),
                    ("order.created", "Order Created"),
                    ("order.paid", "Order Paid"),
                    ("order.confirmed", "Order Confirmed"),
                    ("order.processing", "Order Processing"),
                    ("order.shipped", "Order Shipped"),
                    ("order.delivered", "Order Delivered"),
                    ("order.cancelled", "Order Cancelled"),
                    ("order.refunded", "Order Refunded"),
                    ("refund.processed", "Refund Processed"),
                    ("return.requested", "Return Requested"),
                    ("return.updated", "Return Updated"),
                    ("shipment.created", "Shipment Created"),
                    ("shipment.updated", "Shipment Updated"),
                    ("cart.abandoned", "Cart Abandoned"),
                    ("payment.success", "Payment Success"),
                    ("payment.failed", "Payment Failed"),
                    ("inventory.low_stock", "Low Stock"),
                    ("inventory.out_of_stock", "Out of Stock"),
                    ("inventory.restocked", "Restocked"),
                    ("review.submitted", "Review Submitted"),
                    ("vendor.approved", "Vendor Approved"),
                    ("payout.created", "Payout Created"),
                ],
                max_length=100,
                verbose_name="event",
            ),
        ),
        migrations.AlterField(
            model_name="webhookendpoint",
            name="failure_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Reset on every successful delivery.",
                verbose_name="consecutive failures",
            ),
        ),
        migrations.AlterField(
            model_name="webhookendpoint",
            name="url",
            field=models.URLField(max_length=500, verbose_name="URL"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["action", "created_at"], name="core_audit_action_idx"),
        ),
        migrations.AddField(
            model_name="webhookdelivery",
            name="endpoint",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliveries",
                to="flexcommerce_core.webhookendpoint",
            ),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(
                fields=["status", "next_attempt_at"], name="core_whdelivery_due_idx"
            ),
        ),
    ]
