# Generated by Django 6.0.8 on 2026-09-30 14:46

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import flexcommerce_orders.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="extra data"),
                ),
                (
                    "order_number",
                    models.CharField(max_length=50, unique=True, verbose_name="order number"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, db_index=True, max_length=254, verbose_name="email"
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, verbose_name="phone")),
                (
                    "session_key",
                    models.CharField(blank=True, max_length=40, verbose_name="session key"),
                ),
                ("cart_id", models.UUIDField(blank=True, null=True, verbose_name="cart")),
                (
                    "idempotency_key",
                    models.CharField(blank=True, max_length=100, verbose_name="idempotency key"),
                ),
                (
                    "access_token",
                    models.CharField(
                        default=flexcommerce_orders.models.new_access_token,
                        editable=False,
                        max_length=64,
                        verbose_name="guest access token",
                    ),
                ),
                (
                    "shipping_address",
                    models.JSONField(default=dict, verbose_name="shipping address"),
                ),
                ("billing_address", models.JSONField(default=dict, verbose_name="billing address")),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="items subtotal",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="discount",
                    ),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="shipping",
                    ),
                ),
                (
                    "shipping_vat",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="shipping VAT",
                    ),
                ),
                (
                    "tax_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="VAT total",
                    ),
                ),
                (
                    "grand_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="grand total",
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="amount paid",
                    ),
                ),
                (
                    "amount_refunded",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="amount refunded",
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="NGN", max_length=10, verbose_name="currency"),
                ),
                (
                    "coupon_code",
                    models.CharField(blank=True, max_length=100, verbose_name="coupon code"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("processing", "Processing"),
                            ("partially_shipped", "Partially shipped"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                            ("partially_refunded", "Partially refunded"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=30,
                        verbose_name="status",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("partially_refunded", "Partially refunded"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="payment status",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(blank=True, max_length=30, verbose_name="payment method"),
                ),
                (
                    "payment_provider",
                    models.CharField(blank=True, max_length=50, verbose_name="payment provider"),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True, db_index=True, max_length=200, verbose_name="payment reference"
                    ),
                ),
                (
                    "shipping_method_id",
                    models.UUIDField(blank=True, null=True, verbose_name="shipping method"),
                ),
                (
                    "shipping_method_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="shipping method name"
                    ),
                ),
                (
                    "pickup_station",
                    models.JSONField(blank=True, default=dict, verbose_name="pickup station"),
                ),
                (
                    "estimated_delivery_from",
                    models.DateField(blank=True, null=True, verbose_name="estimated delivery from"),
                ),
                (
                    "estimated_delivery_to",
                    models.DateField(blank=True, null=True, verbose_name="estimated delivery to"),
                ),
                ("vendor_id", models.UUIDField(blank=True, null=True, verbose_name="vendor ID")),
                ("customer_note", models.TextField(blank=True, verbose_name="customer note")),
                ("internal_note", models.TextField(blank=True, verbose_name="internal note")),
                (
                    "cancellation_reason",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="cancellation reason"
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="confirmed at"),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True, verbose_name="paid at")),
                (
                    "shipped_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="shipped at"),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="delivered at"),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="cancelled at"),
                ),
                (
                    "payment_due_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="payment due"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "order",
                "verbose_name_plural": "orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="extra data"),
                ),
                ("event", models.CharField(max_length=50, verbose_name="event")),
                ("message", models.CharField(max_length=500, verbose_name="message")),
                (
                    "is_customer_visible",
                    models.BooleanField(default=True, verbose_name="visible to customer"),
                ),
                ("actor", models.CharField(blank=True, max_length=255, verbose_name="actor")),
                ("data", models.JSONField(blank=True, default=dict, verbose_name="data")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="flexcommerce_orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "order event",
                "verbose_name_plural": "order events",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="extra data"),
                ),
                (
                    "object_id",
                    models.UUIDField(
                        blank=True, db_index=True, null=True, verbose_name="product ID"
                    ),
                ),
                (
                    "parent_product_id",
                    models.UUIDField(blank=True, null=True, verbose_name="parent product ID"),
                ),
                ("product_name", models.CharField(max_length=255, verbose_name="product name")),
                ("product_sku", models.CharField(blank=True, max_length=100, verbose_name="SKU")),
                (
                    "product_data",
                    models.JSONField(blank=True, default=dict, verbose_name="product snapshot"),
                ),
                ("quantity", models.PositiveIntegerField(default=1, verbose_name="quantity")),
                (
                    "unit_price_net",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="unit price (net)"
                    ),
                ),
                (
                    "unit_vat",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="unit VAT",
                    ),
                ),
                (
                    "unit_price_gross",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="unit price (gross)"
                    ),
                ),
                (
                    "vat_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0750"),
                        max_digits=5,
                        verbose_name="VAT rate",
                    ),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="line total (gross)"
                    ),
                ),
                (
                    "line_vat",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="line VAT",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="line discount",
                    ),
                ),
                (
                    "quantity_shipped",
                    models.PositiveIntegerField(default=0, verbose_name="quantity shipped"),
                ),
                (
                    "quantity_returned",
                    models.PositiveIntegerField(default=0, verbose_name="quantity returned"),
                ),
                (
                    "vendor_id",
                    models.UUIDField(
                        blank=True, db_index=True, null=True, verbose_name="vendor ID"
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="commission rate",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="flexcommerce_orders.order",
                        verbose_name="order",
                    ),
                ),
            ],
            options={
                "verbose_name": "order item",
                "verbose_name_plural": "order items",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReturnRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="extra data"),
                ),
                (
                    "reason_code",
                    models.CharField(
                        choices=[
                            ("damaged", "Damaged or defective"),
                            ("wrong_item", "Wrong item delivered"),
                            ("not_as_described", "Not as described"),
                            ("missing_parts", "Missing parts or accessories"),
                            ("changed_mind", "Changed my mind"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                        verbose_name="reason",
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="details")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending review"),
                            ("approved", "Approved — awaiting item"),
                            ("rejected", "Rejected"),
                            ("received", "Item received"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "items",
                    models.JSONField(
                        default=list,
                        help_text='[{"order_item_id": "...", "quantity": 1}]',
                        verbose_name="items",
                    ),
                ),
                ("image_urls", models.JSONField(blank=True, default=list, verbose_name="photos")),
                (
                    "refund_method",
                    models.CharField(
                        choices=[
                            ("original", "Original payment method"),
                            ("wallet", "Store wallet / credit"),
                            ("manual", "Manual (bank transfer / cash)"),
                        ],
                        default="original",
                        max_length=20,
                        verbose_name="refund method",
                    ),
                ),
                ("staff_note", models.TextField(blank=True, verbose_name="staff note")),
                (
                    "received_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="received at"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_returns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="returns",
                        to="flexcommerce_orders.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="return_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "return request",
                "verbose_name_plural": "return requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="extra data"),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=14, verbose_name="amount"),
                ),
                ("reason", models.TextField(verbose_name="reason")),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("original", "Original payment method"),
                            ("wallet", "Store wallet / credit"),
                            ("manual", "Manual (bank transfer / cash)"),
                        ],
                        default="original",
                        max_length=20,
                        verbose_name="method",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                        ],
                        default="requested",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="processed at"),
                ),
                (
                    "reference",
                    models.CharField(blank=True, max_length=200, verbose_name="reference"),
                ),
                (
                    "failure_reason",
                    models.CharField(blank=True, max_length=500, verbose_name="failure reason"),
                ),
                ("items", models.JSONField(blank=True, default=list, verbose_name="items")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refunds",
                        to="flexcommerce_orders.order",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_refunds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "return_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refunds",
                        to="flexcommerce_orders.returnrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "refund",
                "verbose_name_plural": "refunds",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="extra data"),
                ),
                ("carrier", models.CharField(blank=True, max_length=100, verbose_name="carrier")),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True, db_index=True, max_length=200, verbose_name="tracking number"
                    ),
                ),
                (
                    "tracking_url",
                    models.URLField(blank=True, max_length=500, verbose_name="tracking URL"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("dispatched", "Dispatched"),
                            ("in_transit", "In transit"),
                            ("out_for_delivery", "Out for delivery"),
                            ("delivered", "Delivered"),
                            ("failed", "Delivery failed"),
                            ("returned", "Returned to sender"),
                        ],
                        default="dispatched",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "shipped_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="shipped at"),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="delivered at"),
                ),
                (
                    "estimated_delivery",
                    models.DateField(blank=True, null=True, verbose_name="estimated delivery"),
                ),
                (
                    "items",
                    models.JSONField(
                        default=list,
                        help_text='[{"order_item_id": "...", "quantity": 1}]',
                        verbose_name="items",
                    ),
                ),
                ("vendor_id", models.UUIDField(blank=True, null=True, verbose_name="vendor ID")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipments",
                        to="flexcommerce_orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "shipment",
                "verbose_name_plural": "shipments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShipmentEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="extra data"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("dispatched", "Dispatched"),
                            ("in_transit", "In transit"),
                            ("out_for_delivery", "Out for delivery"),
                            ("delivered", "Delivered"),
                            ("failed", "Delivery failed"),
                            ("returned", "Returned to sender"),
                        ],
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, verbose_name="description"),
                ),
                ("location", models.CharField(blank=True, max_length=255, verbose_name="location")),
                ("occurred_at", models.DateTimeField(verbose_name="occurred at")),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="flexcommerce_orders.shipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "shipment event",
                "verbose_name_plural": "shipment events",
                "ordering": ["occurred_at"],
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["user", "status"], name="orders_user_status_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status", "payment_status"], name="orders_status_pay_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["payment_status", "payment_due_at"], name="orders_payment_due_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["created_at"], name="orders_created_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["confirmed_at"], name="orders_confirmed_idx"),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("idempotency_key",),
                name="orders_unique_idempotency_key",
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["content_type", "object_id"], name="orders_item_product_idx"
            ),
        ),
    ]
