# Generated by Django 6.0.8 on 2026-09-30 13:57

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="extra data"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=100, unique=True, verbose_name="code"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                (
                    "coupon_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage Discount"),
                            ("fixed", "Fixed Amount Discount"),
                            ("free_shipping", "Free Shipping"),
                            ("buy_x_get_y", "Buy X Get Y"),
                        ],
                        default="percentage",
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Percentage (0-100) or fixed amount.",
                        max_digits=14,
                        verbose_name="value",
                    ),
                ),
                (
                    "max_discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cap for percentage coupons, e.g. 10% off up to ₦5,000.",
                        max_digits=14,
                        null=True,
                        verbose_name="maximum discount",
                    ),
                ),
                (
                    "buy_quantity",
                    models.PositiveIntegerField(default=0, verbose_name="buy quantity"),
                ),
                (
                    "get_quantity",
                    models.PositiveIntegerField(default=0, verbose_name="get quantity"),
                ),
                (
                    "minimum_cart_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="minimum cart value",
                    ),
                ),
                (
                    "is_stackable",
                    models.BooleanField(
                        default=False,
                        help_text="Reserved for future use.",
                        verbose_name="stackable",
                    ),
                ),
                (
                    "applies_to_all",
                    models.BooleanField(default=True, verbose_name="applies to all products"),
                ),
                (
                    "restricted_categories",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Category ids. Empty = any.",
                        verbose_name="only these categories",
                    ),
                ),
                (
                    "restricted_products",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Product ids. Empty = any.",
                        verbose_name="only these products",
                    ),
                ),
                (
                    "excluded_products",
                    models.JSONField(blank=True, default=list, verbose_name="excluded products"),
                ),
                (
                    "vendor_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Marketplace: only this vendor's products (vendor-funded).",
                        null=True,
                        verbose_name="vendor",
                    ),
                ),
                (
                    "first_order_only",
                    models.BooleanField(default=False, verbose_name="first order only"),
                ),
                (
                    "auto_apply",
                    models.BooleanField(
                        default=False,
                        help_text="Applied without a code when it is the best offer.",
                        verbose_name="automatic promotion",
                    ),
                ),
                (
                    "usage_limit",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="usage limit"),
                ),
                (
                    "per_user_limit",
                    models.PositiveIntegerField(
                        default=1, help_text="0 = unlimited.", verbose_name="per customer limit"
                    ),
                ),
                ("used_count", models.PositiveIntegerField(default=0, verbose_name="used count")),
                (
                    "starts_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="starts at"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="expires at"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="is active")),
            ],
            options={
                "verbose_name": "coupon",
                "verbose_name_plural": "coupons",
                "indexes": [
                    models.Index(fields=["code", "is_active"], name="disc_coupon_code_idx"),
                    models.Index(fields=["expires_at"], name="disc_coupon_exp_idx"),
                    models.Index(fields=["auto_apply", "is_active"], name="disc_coupon_auto_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="FlashSale",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="extra data"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="discount %",
                    ),
                ),
                ("starts_at", models.DateTimeField(verbose_name="starts at")),
                ("ends_at", models.DateTimeField(verbose_name="ends at")),
                ("is_active", models.BooleanField(default=True, verbose_name="is active")),
                (
                    "applicable_products",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Used when the sale has no items. Empty = all products.",
                        verbose_name="applicable product IDs",
                    ),
                ),
            ],
            options={
                "verbose_name": "flash sale",
                "verbose_name_plural": "flash sales",
                "indexes": [
                    models.Index(
                        fields=["starts_at", "ends_at", "is_active"], name="disc_flash_window_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CouponRedemption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="extra data"),
                ),
                (
                    "customer_key",
                    models.CharField(
                        help_text='"user:<id>" or "email:<address>"',
                        max_length=150,
                        verbose_name="customer",
                    ),
                ),
                ("count", models.PositiveIntegerField(default=0, verbose_name="times used")),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to="flexcommerce_discounts.coupon",
                    ),
                ),
            ],
            options={
                "verbose_name": "coupon redemption counter",
                "verbose_name_plural": "coupon redemption counters",
                "unique_together": {("coupon", "customer_key")},
            },
        ),
        migrations.CreateModel(
            name="CouponUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="extra data"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, db_index=True, max_length=254, verbose_name="email"
                    ),
                ),
                (
                    "session_key",
                    models.CharField(blank=True, max_length=40, verbose_name="session key"),
                ),
                (
                    "order_ref",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, verbose_name="order reference"
                    ),
                ),
                (
                    "discount_applied",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="discount applied"
                    ),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="flexcommerce_discounts.coupon",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coupon_usages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "coupon usage",
                "verbose_name_plural": "coupon usages",
                "indexes": [models.Index(fields=["coupon", "user"], name="disc_usage_user_idx")],
            },
        ),
        migrations.CreateModel(
            name="FlashSaleItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="extra data"),
                ),
                ("object_id", models.UUIDField(verbose_name="product ID")),
                (
                    "sale_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Fixed sale price. Blank = the sale's discount percentage.",
                        max_digits=14,
                        null=True,
                        verbose_name="sale price",
                    ),
                ),
                (
                    "quantity_limit",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="units available at sale price"
                    ),
                ),
                (
                    "sold_quantity",
                    models.PositiveIntegerField(default=0, verbose_name="units sold"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="flexcommerce_discounts.flashsale",
                    ),
                ),
            ],
            options={
                "verbose_name": "flash sale item",
                "verbose_name_plural": "flash sale items",
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"], name="disc_flashitem_obj_idx"
                    )
                ],
                "unique_together": {("sale", "content_type", "object_id")},
            },
        ),
    ]
